name: Docker Build & Push

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Docker image tags
        id: vars
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "TAG=prod" >> $GITHUB_ENV
            echo "LATEST=latest" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "develop" ]]; then
            echo "TAG=test" >> $GITHUB_ENV
          else
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./server/hosts/TaskManager.WebApi/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/taskmanager.webapi:${{ env.TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/taskmanager.webapi:${{ github.sha }}${{ env.LATEST && '\n' }}${{ secrets.DOCKERHUB_USERNAME }}/taskmanager.webapi:${{ env.LATEST }}
